### ISSUE TITLE
1.1.0 - NoMethodError: undefined method `on_friendship_created' for nil:NilClass

### ISSUE THREAD

**Issue by S-hack** [sungwoncho/has_friendship#45]
Since I upgraded from 1.0.2 to the latest update, 1.1.0, I get an error when I do a basic friend request:

```
a = User.last
b = User.new
a.friend_request(b)

```

When entering in those commands, I get this error, which looks like an issue with the new callbacks feature. 

```
NoMethodError: undefined method `on_friendship_created' for nil:NilClass

/gems/ruby-2.4.1/gems/has_friendship-1.1.0/lib/has_friendship/friendship.rb:5:in `block in <class:Friendship>'
/gems/ruby-2.4.1/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:396:in `instance_exec'
/gems/ruby-2.4.1/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:396:in `block in make_lambda'
...
/gems/ruby-2.4.1/gems/has_friendship-1.1.0/lib/has_friendship/friendship.rb:46:in `create_relation'
/gems/ruby-2.4.1/gems/has_friendship-1.1.0/lib/has_friendship/friendable.rb:46:in `block in friend_request'
...
/gems/ruby-2.4.1/gems/has_friendship-1.1.0/lib/has_friendship/friendable.rb:45:in `friend_request'

```

All else is in order, and the gem works perfectly once I simply downgrade to 1.0.2

**Comment by chevinbrown** [comment]
@S-hack looks like `b` is a new, but not persisted record.

You can see in L5 of `friendship.rb` that `friend` is expected to be a persisted user. Since it's not persisted (nil), you'll get an `undefined_method` error. 

Is this still an issue?
